version: '1'
services:
  web:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/mcq
      - /mcq/node_modules
    env_file:
      - .env
    networks:
      - webnet
networks:
  webnet: